#!/bin/bash

# Update repositories
sudo apt-get update

# Upgrade existing packages
sudo apt-get dist-upgrade

# Install core utils
sudo apt-get install build-essential
sudo apt-get install curl
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev
sudo apt-get install software-properties-common

# Install Google Chrome
wget -qO - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo apt-key add -
sh -c "printf 'deb http://dl.google.com/linux/deb/ stable main' >> '/etc/apt/sources.list.d/google-chrome.list'"
sudo apt-get install google-chrome-stable
